openapi: 3.0.3
info:
  title: ReservoExtService - 1.0
  version: 1.0.0
  description: Documentazione di esempio per servizio di validazione Sara per
    il contesato Baleari
  contact: {}
x-microcks:
  name: Example API
  version: "1.0.0"
  dispatcher: JSON
servers:
  - url: http://baleari.swagger.io/v2
paths:
  /sara/status-verification:
    post:
      tags:
        - sara
      summary: status-verification
      description: status-verification
      operationId: statusVerification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                destination:
                  type: string
                  example: <string>
                documentNumber:
                  type: string
                  example: <string>
                name:
                  type: string
                  example: <string>
                origin:
                  type: string
                  example: <string>
                secondSurname:
                  type: string
                  example: <string>
                surname:
                  type: string
                  example: <string>
                ticketNumber:
                  type: string
                  example: <string>
                ticketPrice:
                  type: number
                  example: 0
                tipoDoc:
                  type: string
                  example: <int>
                transportType:
                  type: number
                  example: 2
            examples:
              status-verification:
                value:
                  destination: <string>
                  documentNumber: <string>
                  name: <string>
                  origin: <string>
                  secondSurname: <string>
                  surname: <string>
                  ticketNumber: <string>
                  ticketPrice: 0
                  tipoDoc: <int>
                  transportType: 2
      responses:
        '200':
          description: status-verification ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: '{{ randomValue(000,001, 002, 003) }}'
                  message:
                    type: string
                    example: '{{ randomString(64) }}'
                  saraTransCode:
                    type: string
                    example: '{{ randomString(64) }}'
              examples:
                status-verification ok:
                  value:
                    code: '{{ randomValue(000,001, 002, 003) }}'
                    message: '{{ randomString(64) }}'
                    saraTransCode: '{{ randomString(64) }}'
      security:
        - oauth2:
            - write:pets
            - read:pets
  /sara/sara-validate/test-error:
    post:
      tags:
        - sara
      summary: test-error
      description: test-error
      operationId: testError
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                destination:
                  type: string
                  example: <string>
                documentNumber:
                  type: string
                  example: <string>
                name:
                  type: string
                  example: <string>
                origin:
                  type: string
                  example: <string>
                secondSurname:
                  type: string
                  example: <string>
                surname:
                  type: string
                  example: <string>
                ticketNumber:
                  type: string
                  example: <string>
                ticketPrice:
                  type: number
                  example: 0
                tipoDoc:
                  type: string
                  example: <int>
                transportType:
                  type: number
                  example: 2
            examples:
              test-error:
                value:
                  destination: <string>
                  documentNumber: <string>
                  name: <string>
                  origin: <string>
                  secondSurname: <string>
                  surname: <string>
                  ticketNumber: <string>
                  ticketPrice: 0
                  tipoDoc: <int>
                  transportType: 2
      responses:
        '200':
          description: ''
        '500':
          description: test-error
          content:
            text/plain:
              examples:
                test-error:
                  value: ''
      security:
        - oauth2:
            - write:pets
            - read:pets
  /eulisa/status-verification:
    post:
      tags:
        - eu-lisa
      summary: status-verification
      description: status-verification
      operationId: statusVerification1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                carrierID:
                  type: string
                  example: C0949
                nReqID:
                  type: string
                  example: IK99911100
                pngs:
                  type: object
                  properties:
                    png:
                      type: array
                      items:
                        type: object
                        properties:
                          arrivalLocation:
                            type: object
                            properties:
                              arrivalDate:
                                type: string
                                example: '2022-09-20'
                              arrivalLocationCode:
                                type: string
                                example: LTMDK
                              departureDatetime:
                                type: string
                                example: '2022-09-20T11:00:00+02:00'
                              scheduleNo:
                                type: string
                                example: 1324F
                          docs:
                            type: object
                            properties:
                              dateOfBirth:
                                type: string
                                example: '1985-01-01'
                              expiryDate:
                                type: string
                                example: '2025-04-12'
                              givenName:
                                type: string
                                example: Alice
                              issuingState:
                                type: string
                                example: EGY
                              paxNationality:
                                type: string
                                example: EGY
                              sex:
                                type: string
                                example: female
                              surname:
                                type: string
                                example: Anderson
                              travelDocNbr:
                                type: string
                                example: '940227152'
                              travelDocType:
                                type: string
                                example: P
                          eesetiasOutOfScope:
                            type: boolean
                            example: false
                          inTransit:
                            type: boolean
                            example: false
                          multipleEntry:
                            type: boolean
                            example: false
                          pReqID:
                            type: string
                            example: K00001
                      example:
                        - arrivalLocation:
                            arrivalDate: '2022-09-20'
                            arrivalLocationCode: LTMDK
                            departureDatetime: '2022-09-20T11:00:00+02:00'
                            scheduleNo: 1324F
                          docs:
                            dateOfBirth: '1985-01-01'
                            expiryDate: '2025-04-12'
                            givenName: Alice
                            issuingState: EGY
                            paxNationality: EGY
                            sex: female
                            surname: Anderson
                            travelDocNbr: '940227152'
                            travelDocType: P
                          eesetiasOutOfScope: false
                          inTransit: false
                          multipleEntry: false
                          pReqID: K00001
                serviceProviderID:
                  type: string
                  example: S063
                submissionDT:
                  type: string
                  example: '2024-02-08T16:15:00+03:00'
                user:
                  type: string
                  example: SWSDA004
            examples:
              status-verification:
                value:
                  carrierID: C0949
                  nReqID: IK99911100
                  pngs:
                    png:
                      - arrivalLocation:
                          arrivalDate: '2022-09-20'
                          arrivalLocationCode: LTMDK
                          departureDatetime: '2022-09-20T11:00:00+02:00'
                          scheduleNo: 1324F
                        docs:
                          dateOfBirth: '1985-01-01'
                          expiryDate: '2025-04-12'
                          givenName: Alice
                          issuingState: EGY
                          paxNationality: EGY
                          sex: female
                          surname: Anderson
                          travelDocNbr: '940227152'
                          travelDocType: P
                        eesetiasOutOfScope: false
                        inTransit: false
                        multipleEntry: false
                        pReqID: K00001
                  serviceProviderID: S063
                  submissionDT: '2024-02-08T16:15:00+03:00'
                  user: SWSDA004
      responses:
        '200':
          description: status-verification ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  nReqID:
                    type: string
                    example: IK99911100
                  pngStates:
                    type: object
                    properties:
                      pngStateRS:
                        type: array
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                              example: '{{ randomValue(OK,NOK EES, NA) }}'
                            pReqID:
                              type: string
                              example: K00004
                        example:
                          - code: '{{ randomValue(OK,NOK EES, NA) }}'
                            pReqID: K00004
                          - code: '{{ randomValue(OK,NOK EES, NA) }}'
                            pReqID: K00001
                          - code: '{{ randomValue(OK,NOK EES, NA) }}'
                            pReqID: K00002
                  responseDT:
                    type: string
                    example: '2024-09-24T14:50:51.684Z'
              examples:
                status-verification ok:
                  value:
                    nReqID: IK99911100
                    pngStates:
                      pngStateRS:
                        - code: '{{ randomValue(OK,NOK EES, NA) }}'
                          pReqID: K00004
                        - code: '{{ randomValue(OK,NOK EES, NA) }}'
                          pReqID: K00001
                        - code: '{{ randomValue(OK,NOK EES, NA) }}'
                          pReqID: K00002
                    responseDT: '2024-09-24T14:50:51.684Z'
  /eulisa/status-verification/test-error:
    post:
      tags:
        - eu-lisa
      summary: test-error
      description: test-error
      operationId: testError1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                carrierID:
                  type: string
                  example: C0949
                nReqID:
                  type: string
                  example: IK99911100
                pngs:
                  type: object
                  properties:
                    png:
                      type: array
                      items:
                        type: object
                        properties:
                          arrivalLocation:
                            type: object
                            properties:
                              arrivalDate:
                                type: string
                                example: '2022-09-20'
                              arrivalLocationCode:
                                type: string
                                example: LTMDK
                              departureDatetime:
                                type: string
                                example: '2022-09-20T11:00:00+02:00'
                              scheduleNo:
                                type: string
                                example: 1324F
                          docs:
                            type: object
                            properties:
                              dateOfBirth:
                                type: string
                                example: '1985-01-01'
                              expiryDate:
                                type: string
                                example: '2025-04-12'
                              givenName:
                                type: string
                                example: Alice
                              issuingState:
                                type: string
                                example: EGY
                              paxNationality:
                                type: string
                                example: EGY
                              sex:
                                type: string
                                example: female
                              surname:
                                type: string
                                example: Anderson
                              travelDocNbr:
                                type: string
                                example: '940227152'
                              travelDocType:
                                type: string
                                example: P
                          eesetiasOutOfScope:
                            type: boolean
                            example: false
                          inTransit:
                            type: boolean
                            example: false
                          multipleEntry:
                            type: boolean
                            example: false
                          pReqID:
                            type: string
                            example: K00001
                      example:
                        - arrivalLocation:
                            arrivalDate: '2022-09-20'
                            arrivalLocationCode: LTMDK
                            departureDatetime: '2022-09-20T11:00:00+02:00'
                            scheduleNo: 1324F
                          docs:
                            dateOfBirth: '1985-01-01'
                            expiryDate: '2025-04-12'
                            givenName: Alice
                            issuingState: EGY
                            paxNationality: EGY
                            sex: female
                            surname: Anderson
                            travelDocNbr: '940227152'
                            travelDocType: P
                          eesetiasOutOfScope: false
                          inTransit: false
                          multipleEntry: false
                          pReqID: K00001
                serviceProviderID:
                  type: string
                  example: S063
                submissionDT:
                  type: string
                  example: '2024-02-08T16:15:00+03:00'
                user:
                  type: string
                  example: SWSDA004
            examples:
              test-error:
                value:
                  carrierID: C0949
                  nReqID: IK99911100
                  pngs:
                    png:
                      - arrivalLocation:
                          arrivalDate: '2022-09-20'
                          arrivalLocationCode: LTMDK
                          departureDatetime: '2022-09-20T11:00:00+02:00'
                          scheduleNo: 1324F
                        docs:
                          dateOfBirth: '1985-01-01'
                          expiryDate: '2025-04-12'
                          givenName: Alice
                          issuingState: EGY
                          paxNationality: EGY
                          sex: female
                          surname: Anderson
                          travelDocNbr: '940227152'
                          travelDocType: P
                        eesetiasOutOfScope: false
                        inTransit: false
                        multipleEntry: false
                        pReqID: K00001
                  serviceProviderID: S063
                  submissionDT: '2024-02-08T16:15:00+03:00'
                  user: SWSDA004
      responses:
        '200':
          description: ''
        '500':
          description: test-error
          content: {}
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          tokenUrl: ''
          scopes:
            read:pets: read:pets
            write:pets: write:pets
tags:
  - name: sara
  - name: eu-lisa
